In [11]:
! pip install pandas 

ERROR: Could not find a version that satisfies the requirement xelatex (from versions: none)
ERROR: No matching distribution found for xelatex


In [1]:
import pandas as pd
import numpy as np

In [2]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [3]:
# Dataframe creation
df = pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=["ROW1","ROW2","ROW3","ROW4","ROW5"],columns=["COLUMN1","COLUMN2","COLUMN3","COLUMN4"])

In [4]:
df

COLUMN1  COLUMN2  COLUMN3  COLUMN4
ROW1        0        1        2        3
ROW2        4        5        6        7
ROW3        8        9       10       11
ROW4       12       13       14       15
ROW5       16       17       18       19

In [5]:
df.head(3)

COLUMN1  COLUMN2  COLUMN3  COLUMN4
ROW1        0        1        2        3
ROW2        4        5        6        7
ROW3        8        9       10       11

In [6]:
df.tail(3)

COLUMN1  COLUMN2  COLUMN3  COLUMN4
ROW3        8        9       10       11
ROW4       12       13       14       15
ROW5       16       17       18       19

In [7]:
df.head()  ## by default top 5 records 

COLUMN1  COLUMN2  COLUMN3  COLUMN4
ROW1        0        1        2        3
ROW2        4        5        6        7
ROW3        8        9       10       11
ROW4       12       13       14       15
ROW5       16       17       18       19

In [8]:
df.tail()  ## by default last 5 records 

COLUMN1  COLUMN2  COLUMN3  COLUMN4
ROW1        0        1        2        3
ROW2        4        5        6        7
ROW3        8        9       10       11
ROW4       12       13       14       15
ROW5       16       17       18       19

In [9]:
type(df)

pandas.core.frame.DataFrame

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, ROW1 to ROW5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   COLUMN1  5 non-null      int32
 1   COLUMN2  5 non-null      int32
 2   COLUMN3  5 non-null      int32
 3   COLUMN4  5 non-null      int32
dtypes: int32(4)
memory usage: 120.0+ bytes


In [11]:
df.describe()

COLUMN1    COLUMN2    COLUMN3    COLUMN4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [13]:
##Indexing

## columname,rowindex[Loc],rowindex columnindex[.iloc]

df.head()

COLUMN1  COLUMN2  COLUMN3  COLUMN4
ROW1        0        1        2        3
ROW2        4        5        6        7
ROW3        8        9       10       11
ROW4       12       13       14       15
ROW5       16       17       18       19

In [14]:
## Method 1- columname
df[['COLUMN1',"COLUMN2","COLUMN3"]] ## if there is more than one column then we use double square bracket

COLUMN1  COLUMN2  COLUMN3
ROW1        0        1        2
ROW2        4        5        6
ROW3        8        9       10
ROW4       12       13       14
ROW5       16       17       18

In [16]:
df["COLUMN3"]

ROW1     2
ROW2     6
ROW3    10
ROW4    14
ROW5    18
Name: COLUMN3, dtype: int32

In [17]:
type(df["COLUMN3"])

pandas.core.series.Series

In [18]:
type(df[['COLUMN1',"COLUMN2","COLUMN3"]])

pandas.core.frame.DataFrame

In [19]:
## Method 2 - rowindex[Loc]
df.loc['ROW3']

COLUMN1     8
COLUMN2     9
COLUMN3    10
COLUMN4    11
Name: ROW3, dtype: int32

In [20]:
type(df.loc['ROW3'])

pandas.core.series.Series

In [21]:
df.loc[['ROW2','ROW1']]

COLUMN1  COLUMN2  COLUMN3  COLUMN4
ROW2        4        5        6        7
ROW1        0        1        2        3

In [22]:
type(df.loc[['ROW2','ROW1']])

pandas.core.frame.DataFrame

In [23]:
## Method 3 - rowindex columnindex[.iloc]
df.iloc[2:4,0:2]

COLUMN1  COLUMN2
ROW3        8        9
ROW4       12       13

In [24]:
type(df.iloc[2:4,0:2])

pandas.core.frame.DataFrame

In [25]:
df.iloc[2:,1:]

COLUMN2  COLUMN3  COLUMN4
ROW3        9       10       11
ROW4       13       14       15
ROW5       17       18       19

In [26]:
df.iloc[:,1:]

COLUMN2  COLUMN3  COLUMN4
ROW1        1        2        3
ROW2        5        6        7
ROW3        9       10       11
ROW4       13       14       15
ROW5       17       18       19

In [27]:
## convert dataframe into arrays
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

In [28]:
## operations

df

COLUMN1  COLUMN2  COLUMN3  COLUMN4
ROW1        0        1        2        3
ROW2        4        5        6        7
ROW3        8        9       10       11
ROW4       12       13       14       15
ROW5       16       17       18       19

In [29]:
df.isnull().sum()

COLUMN1    0
COLUMN2    0
COLUMN3    0
COLUMN4    0
dtype: int64

In [30]:
df = pd.DataFrame(data=[[1,np.nan,2],[1,3,4]],index=["ROW1","ROW2"],columns=["COLUMN1","COLUMN2","COLUMN3"]) ## Nan is null

In [31]:
df

COLUMN1  COLUMN2  COLUMN3
ROW1        1      NaN        2
ROW2        1      3.0        4

In [32]:
df.isnull().sum()

COLUMN1    0
COLUMN2    1
COLUMN3    0
dtype: int64

In [33]:
df.isnull()

COLUMN1  COLUMN2  COLUMN3
ROW1    False     True    False
ROW2    False    False    False

In [36]:
df.isnull().sum() ==0

COLUMN1     True
COLUMN2    False
COLUMN3     True
dtype: bool

In [37]:
df

COLUMN1  COLUMN2  COLUMN3
ROW1        1      NaN        2
ROW2        1      3.0        4

In [40]:
df['COLUMN3'].value_counts()

COLUMN3
2    1
4    1
Name: count, dtype: int64

In [38]:
df['COLUMN1'].unique()

array([1], dtype=int64)

In [39]:
df['COLUMN3'].unique()

array([2, 4], dtype=int64)

In [41]:
df = pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=["ROW1","ROW2","ROW3","ROW4","ROW5"],columns=["COLUMN1","COLUMN2","COLUMN3","COLUMN4"])

In [42]:
df

COLUMN1  COLUMN2  COLUMN3  COLUMN4
ROW1        0        1        2        3
ROW2        4        5        6        7
ROW3        8        9       10       11
ROW4       12       13       14       15
ROW5       16       17       18       19

In [43]:
df['COLUMN3'].unique()

array([ 2,  6, 10, 14, 18])

In [44]:
df>2

COLUMN1  COLUMN2  COLUMN3  COLUMN4
ROW1    False    False    False     True
ROW2     True     True     True     True
ROW3     True     True     True     True
ROW4     True     True     True     True
ROW5     True     True     True     True

In [45]:
df['COLUMN3']>4

ROW1    False
ROW2     True
ROW3     True
ROW4     True
ROW5     True
Name: COLUMN3, dtype: bool