In [3]:
## import the library
import numpy as np

In [3]:
lst=[1,2,3,4]
arr=np.array(lst)

In [4]:
arr

array([1, 2, 3, 4])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.shape

(4,)

In [7]:
# 2-D arrays
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[3,4,5,6,7]

arr1=np.array([lst1,lst2,lst3])

In [8]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [9]:
arr1.shape

(3, 5)

In [10]:
#indexing
arr

array([1, 2, 3, 4])

In [11]:
arr[3]

4

In [12]:
#elements change
arr[3]=5
arr

array([1, 2, 3, 5])

In [13]:
arr[1:3]

array([2, 3])

In [14]:
arr[-1] #last elements

5

In [15]:
arr[:-1]

array([1, 2, 3])

In [16]:
arr[::-1] #reverse the elements

array([5, 3, 2, 1])

In [17]:
arr[:]

array([1, 2, 3, 5])

In [18]:
arr[::-2]

array([5, 2])

In [19]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [20]:
arr1[:,1]

array([2, 3, 4])

In [21]:
arr1[1,2]

4

In [22]:
arr1[2,4]

7

In [23]:
arr1[1:,1:3]

array([[3, 4],
       [4, 5]])

In [24]:
arr1[1:,3:]

array([[5, 6],
       [6, 7]])

In [26]:
arr1[:,3:]

array([[4, 5],
       [5, 6],
       [6, 7]])

In [27]:
arr1[:,3:].shape

(3, 2)

In [28]:
##EDA 
arr

array([1, 2, 3, 5])

In [29]:
arr<2

array([ True, False, False, False])

In [30]:
arr[arr<2]

array([1])

In [31]:
arr1.shape

(3, 5)

In [32]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [33]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [34]:
arr1.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 3, 4, 5, 6, 7]])

In [35]:
arr1.reshape(15,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [2],
       [3],
       [4],
       [5],
       [6],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [36]:
##mechanism to create an array
np.arange(1,10,1) ### arange(start,end,step)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [38]:
np.arange(1,20,2).reshape(2,5) 

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [39]:
np.arange(1,20,2).reshape(10,1)

array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11],
       [13],
       [15],
       [17],
       [19]])

In [40]:
np.arange(1,20,2).reshape(5,2,1)

array([[[ 1],
        [ 3]],

       [[ 5],
        [ 7]],

       [[ 9],
        [11]],

       [[13],
        [15]],

       [[17],
        [19]]])

In [42]:
arr

array([1, 2, 3, 5])

In [43]:
arr*arr

array([ 1,  4,  9, 25])

In [44]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [45]:
arr1*arr1

array([[ 1,  4,  9, 16, 25],
       [ 4,  9, 16, 25, 36],
       [ 9, 16, 25, 36, 49]])

In [46]:
arr1*2

array([[ 2,  4,  6,  8, 10],
       [ 4,  6,  8, 10, 12],
       [ 6,  8, 10, 12, 14]])

In [47]:
# arrarys fill with 1
np.ones((5,3)) 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [48]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [75]:
np.random.randint(10,50)

20

In [4]:
np.random.randint(10,50,4) # randint( a,b,c) where numbers are in between a and b AND c will be the size of 1-D arrays

array([40, 12, 43, 49])

In [110]:
np.random.randint(10,50,4).reshape(2,2)

array([[47, 31],
       [24, 36]])

In [131]:
np.random.randn(5,6)

array([[-0.29092583, -0.87296981, -0.28181289,  1.1487481 ,  0.67347681,
        -1.07633107],
       [-0.04316447, -0.65128993,  0.32025422,  0.02101811,  0.40721236,
        -1.17141534],
       [-1.15644017,  0.43725124,  1.34497257,  0.10525914, -0.73083222,
         0.16478884],
       [-1.02975683,  2.11443162, -1.8921548 ,  1.19968455, -1.56865603,
        -0.29386256],
       [ 1.65183441, -2.32756666, -0.58032572, -1.23526366, -1.23952349,
        -0.60125531]])

In [132]:
np.random.random_sample((4,7))

array([[0.76771866, 0.1161727 , 0.69284634, 0.2486592 , 0.19068405,
        0.02712543, 0.59834299],
       [0.27631982, 0.11592   , 0.48679802, 0.88963437, 0.20313744,
        0.42829487, 0.05884864],
       [0.64092819, 0.17118948, 0.47381664, 0.92275172, 0.830659  ,
        0.05455656, 0.72568595],
       [0.94851046, 0.01834461, 0.24309619, 0.25235365, 0.45916759,
        0.22285255, 0.84692534]])